{
 "title": "ETD Log Collector",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_node_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(etd_info{namespace=\"$namespace\", namespace=~\".*7*0\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs by Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(etd_listener_msg_counter_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Logs by Instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(etd_listener_msg_counter_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Logs by Port",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (port) (rate(etd_listener_msg_counter_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Total Processing Throughput by Client",
   "type": "timeseries",
   "description": "Total Throughput of all Log Collectors",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client) (rate(etd_listener_msg_counter_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Total Processing Throughput",
   "type": "timeseries",
   "description": "Total Throughput of all Log Collectors",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(etd_listener_msg_counter_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  { "title": "Details of Selected Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Processing Throughput by Port",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (protocol, port) (rate(etd_listener_msg_counter_total{namespace=\"$instance\"}[5m]))",
     "legendFormat": "{{protocol}} {{port}}"
    },
    {
     "expr": "sum (rate(etd_listener_msg_counter_total{namespace=\"$instance\"}[5m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Too Large Packages Rejected by Client (Top10)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etd_log_size_exceeded_total{namespace=\"$instance\"}",
     "legendFormat": "{{client}} - {{port}}({{protocol}})"
    }
   ]
  },
  {
   "title": "Failed Authentications by Client and Port - Average Per Second over the last 5 Minutes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client) (rate(etd_failed_authentication_total{namespace=\"$instance\"}[5m]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Logs by Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (protocol) (etd_listener_msg_counter_total{namespace=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Logs by Client (Top10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (client) (etd_listener_msg_counter_total{namespace=\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Limiter Waiting Threads",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "resilience4j_ratelimiter_waiting_threads{namespace=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Limiter Available Permissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "resilience4j_ratelimiter_available_permissions{namespace=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Open Connections and Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (protocol,port) (etd_open_connections{namespace=\"$instance\"})",
     "legendFormat": "{{protocol}} {{port}} "
    },
    {
     "expr": "etd_limit_connection{namespace=\"$instance\"}",
     "legendFormat": "Connection Limit {{port}}({{protocol}})"
    }
   ]
  },
  {
   "title": "Internal Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etd_queue_size{namespace=\"$instance\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$instance\"}[30s]) * 100",
     "legendFormat": "CPU Core Usage"
    }
   ]
  },
  {
   "title": "Java Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", namespace=\"$instance\"}/1024/1024",
     "legendFormat": "Memory Used (MB)"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", namespace=\"$instance\"}/1024/1024",
     "legendFormat": "Memory Max (MB)"
    }
   ]
  },
  {
   "title": "Java Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "jvm_threads_state{namespace=\"$instance\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_peak{namespace=\"$instance\"}",
     "legendFormat": "Peak"
    }
   ]
  }
 ]
}