{
 "title": "ETD Coldstorage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(etd_msg_counter_total,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(etd_msg_counter_total{container=\"etds-cw\", namespace=\"ecs-etd-support0012\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput (Total)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (rate(etd_msg_counter_total{namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(etd_msg_counter_total{instance=\"$instance\"}[2m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Internal Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "etd_queue_size{instance=\"$instance\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"etds-cw\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU Core Usage"
    }
   ]
  },
  {
   "title": "Java Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=\"$instance\"}/1024/1024",
     "legendFormat": "Memory Used (MB)"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}/1024/1024",
     "legendFormat": "Memory Max (MB)"
    }
   ]
  },
  {
   "title": "Java Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "jvm_threads_state{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\"}",
     "legendFormat": "Peak"
    }
   ]
  }
 ]
}