{
 "title": "SFTPGo",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(sftpgo_active_connections, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(sftpgo_active_connections, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Transfer Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_download_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_upload_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_download_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_upload_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_download_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_upload_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    },
    {
     "expr": "sum by (job) ( rate(sftpgo_http_client_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_http_server_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sftpgo_active_connections{namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Authentication Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n"
    }
   ]
  },
  { "title": "Data Transfer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Data Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_download_size{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_upload_size{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Data Transfer Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_downloads_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_uploads_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_download_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_upload_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  { "title": "SFTPFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Data Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_download_size{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_upload_size{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Data Transfer Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_downloads_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_uploads_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_download_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_sftpfs_upload_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  { "title": "HTTPFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Data Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_download_size{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_upload_size{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Data Transfer Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_downloads_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_uploads_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_download_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "downloads ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_httpfs_upload_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "uploads ({{`{{job}}`}})"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_http_req_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Requests All ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_http_req_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Requests Ok ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) ( rate(sftpgo_http_client_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Client errors ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_http_server_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Server errors ({{`{{job}}`}})"
    }
   ]
  },
  { "title": "Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "All ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_idp_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "idp ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_key_and_keyboard_int_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key + keyboard interactive ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_key_and_password_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key + password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_keyboard_interactive_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "keyboard interactive ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_password_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "Password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_public_key_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_and_pwd_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "TLS certificate+password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "TLS certificate ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Login Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "All ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_idp_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "idp ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_key_and_keyboard_int_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key + keyboard interactive ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_key_and_password_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key + password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_keyboard_interactive_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "keyboard interactive ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_password_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "Password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_public_key_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_and_pwd_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "TLS certificate+password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "TLS certificate ({{`{{job}}`}})"
    }
   ]
  },
  {
   "title": "Login Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "All ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_idp_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "idp ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_key_and_keyboard_int_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key + keyboard interactive ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_key_and_password_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key + password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_keyboard_interactive_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "keyboard interactive ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_password_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "Password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_public_key_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "public key ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_and_pwd_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "TLS certificate+password ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "TLS certificate ({{`{{job}}`}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_no_auth_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))\n",
     "legendFormat": "Client timeout ({{`{{job}}`}})"
    }
   ]
  }
 ]
}