#!/bin/sh
HIGHEST_MAJOR_VERSION='0'
HIGHEST_MINOR_VERSION='0'
HIGHEST_PATCH_VERSION='0'
HIGHEST_SUB_PATCH_VERSION='0'
HIGHEST_RELEASE_VERSION='0'
CPIDS_RELEASES=$(ls /staging/cpids/Build/ | grep GOLD-PRD-CPIDS-DSOD | tr '\n' ' ')

for release in $CPIDS_RELEASES
do
  CPIDS_RELEASE=$(echo $release | cut -d'-' -f5)
  CPIDS_MAJOR_VERSION=$(echo $CPIDS_RELEASE | cut -d'.' -f1)
  CPIDS_MINOR_VERSION=$(echo $CPIDS_RELEASE | cut -d'.' -f2)
  CPIDS_PATCH_VERSION=$(echo $CPIDS_RELEASE | cut -d'.' -f3)
  CPIDS_SUB_PATCH_VERSION=$(echo $CPIDS_RELEASE | cut -d'.' -f4)
  CPIDS_RELEASE_VERSION=$(echo ${release: -1})
  if [[ $CPIDS_MAJOR_VERSION -gt $HIGHEST_MAJOR_VERSION ]]
  then
    HIGHEST_MAJOR_VERSION=$CPIDS_MAJOR_VERSION
    HIGHEST_MINOR_VERSION='0'
    HIGHEST_PATCH_VERSION='0'
    HIGHEST_SUB_PATCH_VERSION='0'
    HIGHEST_RELEASE_VERSION='0'
  fi
  if [[ $CPIDS_MINOR_VERSION -gt $HIGHEST_MINOR_VERSION ]]
  then
    HIGHEST_MINOR_VERSION=$CPIDS_MINOR_VERSION
    HIGHEST_PATCH_VERSION='0'
    HIGHEST_SUB_PATCH_VERSION='0'
    HIGHEST_RELEASE_VERSION='0'
  fi
  if [[ $CPIDS_PATCH_VERSION -gt $HIGHEST_PATCH_VERSION ]]
  then
    HIGHEST_PATCH_VERSION=$CPIDS_PATCH_VERSION
    HIGHEST_SUB_PATCH_VERSION='0'
    HIGHEST_RELEASE_VERSION='0'
  fi
  if [[ $CPIDS_SUB_PATCH_VERSION -gt $HIGHEST_SUB_PATCH_VERSION ]]
  then
    HIGHEST_SUB_PATCH_VERSION=$CPIDS_SUB_PATCH_VERSION
    HIGHEST_RELEASE_VERSION='0'
  fi
  if [[ $CPIDS_RELEASE_VERSION -gt $HIGHEST_RELEASE_VERSION ]]
  then
    HIGHEST_RELEASE_VERSION=$CPIDS_RELEASE_VERSION
  fi
done
# Output full release name
echo "GOLD-PRD-CPIDS-DSOD-${HIGHEST_MAJOR_VERSION}.${HIGHEST_MINOR_VERSION}.${HIGHEST_PATCH_VERSION}.${HIGHEST_SUB_PATCH_VERSION}-TAR-V${HIGHEST_RELEASE_VERSION}"
