#!/bin/sh
HIGHEST_RELEASE_YEAR='0'
HIGHEST_MAJOR_VERSION='0'
HIGHEST_MINOR_VERSION='0'
HIGHEST_RELEASE_VERSION='0'
SAP_RELEASES=$(ls /staging/ibp/Build/ | grep "GOLD-PRD" | tr '\n' ' ')

for release in $SAP_RELEASES
do
  SAP_RELEASE_YEAR=$(echo $release | cut -d'-' -f3)
  SAP_MAJOR_VERSION=$(echo $release | cut -d'-' -f4 | sed 's/HFC//')
  SAP_MINOR_VERSION=$(echo $release | cut -d'-' -f5 | sed 's/EP//')
  SAP_RELEASE_VERSION=$(echo ${release: -1})
  if [[ $SAP_RELEASE_YEAR -gt $HIGHEST_RELEASE_YEAR ]]
  then
    HIGHEST_RELEASE_YEAR=$SAP_RELEASE_YEAR
    HIGHEST_MAJOR_VERSION='0'
    HIGHEST_MINOR_VERSION='0'
    HIGHEST_RELEASE_VERSION='0'
  fi
  if [[ ${SAP_MAJOR_VERSION#0} -gt ${HIGHEST_MAJOR_VERSION#0} ]]
  then
    HIGHEST_MAJOR_VERSION=$SAP_MAJOR_VERSION
    HIGHEST_MINOR_VERSION='0'
    HIGHEST_RELEASE_VERSION='0'
  fi
  if [[ ${SAP_MINOR_VERSION#0} -gt ${HIGHEST_MINOR_VERSION#0} ]]
  then
    HIGHEST_MINOR_VERSION=$SAP_MINOR_VERSION
    HIGHEST_RELEASE_VERSION='0'
  fi
  if [[ $SAP_RELEASE_VERSION -gt $HIGHEST_RELEASE_VERSION ]]
  then
    HIGHEST_RELEASE_VERSION=$SAP_RELEASE_VERSION
  fi
done
# Output full release name
echo "GOLD-PRD-${HIGHEST_RELEASE_YEAR}-HFC${HIGHEST_MAJOR_VERSION}-EP${HIGHEST_MINOR_VERSION}-TAR-V${HIGHEST_RELEASE_VERSION}"